/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: e-restrepo1114 (https://sketchfab.com/EmanuelRestrepoVelez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/z1000-2014-70cecfa5568347428c5ad72e9a156be9
Title: Z1000 2014
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import z1000 from "../assets/models/z1000.glb"

export function Z1000({ color, sliderValue, ...props }) {
  const { nodes, materials } = useGLTF(z1000)

  if (materials.negrobrillante) {
    materials.negrobrillante.color.set(color)
  }
  if (materials.cobre) {
    materials.cobre.color.set(color)
  }

  return (
    <group
      {...props}
      dispose={null}
      rotation={[-0.1, sliderValue, 0]}
      scale={0.002}
      position={[0, -0.2, 0]}
    >
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, -8.76, -13.564]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial.geometry}
              material={materials.negrobrillante}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_1.geometry}
              material={materials.negromate}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_2.geometry}
              material={materials.aluminio}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_3.geometry}
              material={materials.cobre}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_4.geometry}
              material={materials.cobre_0}
            />
          </group>
          <group scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_5.geometry}
              material={materials.negrobrillante}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_6.geometry}
              material={materials.negromate}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_7.geometry}
              material={materials.aluminio}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_8.geometry}
              material={materials.cobre}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_9.geometry}
              material={materials.cobre_0}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.defaultMaterial_10.geometry}
              material={materials.vidrio}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(z1000)
